# Generated by Django 5.0.1 on 2024-04-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.type'),
            preserve_default=False,
        ),
    ]
